app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['middleware' => 'web'], function() {


    Route::get('/', function () {
        return view('welcome');
    });
    Route::get('/home', 'HomeController@index');

    Route::auth();

    Route::group(['prefix' => 'admin','middleware'=>'auth.checkrole:admin', 'as' => 'admin.'], function() {

        Route::get('categories', ['as' => 'categories.index', 'uses' => 'CategoriesController@index']);
        Route::get('categories/create', ['as' => 'categories.create', 'uses' => 'CategoriesController@create']);
        Route::get('categories/edit/{id}', ['as' => 'categories.edit', 'uses' => 'CategoriesController@edit']);
        Route::post('categories/store', ['as' => 'categories.store', 'uses' => 'CategoriesController@store']);
        Route::post('categories/update/{id}', ['as' => 'categories.update', 'uses' => 'CategoriesController@update']);

        Route::get('clients', ['as' => 'clients.index', 'uses' => 'ClientsController@index']);
        Route::get('clients/create', ['as' => 'clients.create', 'uses' => 'ClientsController@create']);
        Route::get('clients/edit/{id}', ['as' => 'clients.edit', 'uses' => 'ClientsController@edit']);
        Route::get('clients/destroy/{id}', ['as' => 'clients.destroy', 'uses' => 'ClientsController@destroy']);
        Route::post('clients/store', ['as' => 'clients.store', 'uses' => 'ClientsController@store']);
        Route::post('clients/update/{id}', ['as' => 'clients.update', 'uses' => 'ClientsController@update']);

        Route::get('products', ['as' => 'products.index', 'uses' => 'ProductsController@index']);
        Route::get('products/create', ['as' => 'products.create', 'uses' => 'ProductsController@create']);
        Route::get('products/edit/{id}', ['as' => 'products.edit', 'uses' => 'ProductsController@edit']);
        Route::post('products/store', ['as' => 'products.store', 'uses' => 'ProductsController@store']);
        Route::post('products/update/{id}', ['as' => 'products.update', 'uses' => 'ProductsController@update']);
        Route::get('products/destroy/{id}', ['as' => 'products.destroy', 'uses' => 'ProductsController@destroy']);

        Route::get('orders', ['as' => 'orders.index', 'uses' => 'OrdersController@index']);
        Route::get('orders/{id}', ['as' => 'orders.edit', 'uses' => 'OrdersController@edit']);
        Route::post('orders/update/{id}', ['as' => 'orders.update', 'uses' => 'OrdersController@update']);

        Route::get('cupoms', ['as' => 'cupoms.index', 'uses' => 'CupomsController@index']);
        Route::get('cupoms/create', ['as' => 'cupoms.create', 'uses' => 'CupomsController@create']);
        Route::post('cupoms/store', ['as' => 'cupoms.store', 'uses' => 'CupomsController@store']);



    });

    Route::group(['prefix' => 'customer', 'as' => 'customer.'], function() {

        Route::get('order', ['as' => 'order.index', 'uses' => 'CheckoutController@index']);
        Route::get('order/create', ['as' => 'order.create', 'uses' => 'CheckoutController@create']);
        Route::post('order/store', ['as' => 'order.store', 'uses' => 'CheckoutController@store']);

    });
    Route::group(['middleware'=>'cors'], function() {

        Route::post('oauth/access_token', function () {
            return Response::json(Authorizer::issueAccessToken());
        });

        Route::group(['prefix' => 'api', 'as' => 'api.', 'middleware' => 'oauth'], function () {

            Route::group(['prefix' => 'client', 'as' => 'client.', 'middleware' => 'oauth.checkrole:client'], function () {
                Route::resource('order', 'Api\Client\ClientCheckoutController', ['except' => ['create', 'edit', 'destroy']]);
                Route::get('products','Api\Client\ClientProductController@index');
            });

            Route::group(['prefix' => 'deliveryman', 'as' => 'deliveryman.', 'middleware' => 'oauth.checkrole:deliveryman'], function () {
                Route::resource('order', 'Api\Deliveryman\DeliverymanCheckoutController', ['except' => ['create', 'edit', 'destroy', 'store']]);
                Route::patch('order/{id}/update-status', [
                    'uses' => 'Api\Deliveryman\DeliverymanCheckoutController@updateStatus',
                    'as' => 'orders.update_status'
                ]);
                Route::post('order/{id}/geo',['as'=>'orders.geo','uses'=>'Api\Deliveryman\DeliverymanCheckoutController@geo']);
            });

            Route::get('authenticated','Api\UserController@authenticated');
            Route::patch('device_token','Api\UserController@updateDeviceToken');
            Route::get('cupom/{code}','Api\CupomController@show');
        });

    });
});

app/Models/Client.php
<?php

namespace CodeDelivery\Models;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Client extends Model implements Transformable
{
    use TransformableTrait;

    //
    protected $fillable = [
        'user_id',
        'phone',
        'address',
        'city',
        'state',
        'zipcode'
    ];


    public function user()
    {
        return $this->hasOne(User::class, 'id','user_id');
    }

}

app/Http/Controllers/Api/Client/ClientCheckoutController.php
<?php

namespace CodeDelivery\Http\Controllers\Api\Client;

use CodeDelivery\Http\Controllers\Controller;
use CodeDelivery\Http\Requests;
use CodeDelivery\Http\Requests\CheckoutRequest;
use CodeDelivery\Repositories\OrderRepository;
use CodeDelivery\Repositories\ProductRepository;
use CodeDelivery\Repositories\UserRepository;
use CodeDelivery\Services\OrderService;
use Illuminate\Http\Request;
use LucaDegasperi\OAuth2Server\Facades\Authorizer;

class ClientCheckoutController extends Controller
{

    private $repository;
    private $userRepository;
    private $productRepository;

    private $with = ['client','cupom','items'];

    public function __construct(
        OrderRepository $repository,
        UserRepository $userRepository,
        ProductRepository $productRepository,
        OrderService $orderService
    )
    {

        $this->repository = $repository;
        $this->userRepository = $userRepository;
        $this->productRepository = $productRepository;
        $this->service = $orderService;

    }

    public function index()
    {
        $id = Authorizer::getResourceOwnerId();
        $clientId = $this->userRepository->find($id)->client->id;

        $orders = $this->repository
            ->skipPresenter(false)
            ->scopeQuery(function($query) use($clientId){
                return $query->where('client_id','=',$clientId);
        })->paginate();

        return $orders;
    }
    public function create()
    {
        $products = $this->productRepository->listas();
        return view('customer.order.create',compact('products'));
    }

    public function show($id)
    {
        $idUser = Authorizer::getResourceOwnerId();
        return $this->repository
            ->skipPresenter(false)
            ->getByIdAndClient($id,$idUser);
    }

    public function store(CheckoutRequest $request)
    {
        $data = $request->all();

        $id = Authorizer::getResourceOwnerId();
        $clientId = $this->userRepository->find($id)->client->id;
        $data['client_id'] = $clientId;
        $o = $this->service->create($data);
        $o = $this->repository
            ->skipPresenter(false)
            ->find($o->id);

        return $o;
    }

}

app/Http/Controllers/Api/Client/ClientProductController.php
<?php

namespace CodeDelivery\Http\Controllers\Api\Client;

use CodeDelivery\Http\Controllers\Controller;
use CodeDelivery\Http\Requests;
use CodeDelivery\Repositories\ProductRepository;
use Illuminate\Http\Request;
use LucaDegasperi\OAuth2Server\Facades\Authorizer;

class ClientProductController extends Controller
{

    private $repository;

    private $with = ['product'];

    public function __construct(ProductRepository $repository)
    {
        $this->repository = $repository;
    }

    public function index()
    {
        $orders = $this->repository
            ->skipPresenter(false)
            ->all();

        return $orders;
    }
}

app/Http/Controllers/ClientsController.php
<?php

namespace CodeDelivery\Http\Controllers;

use CodeDelivery\Http\Requests\AdminClientRequest;
use CodeDelivery\Services\ClientService;
use CodeDelivery\Repositories\ClientRepository;
use CodeDelivery\Http\Requests;
use CodeDelivery\Repositories\UserRepositoryEloquent;
use Illuminate\Http\Request;

class ClientsController extends Controller
{
    public function __construct(ClientRepository $repository, ClientService $clientService)
    {
        $this->repository       = $repository;
        $this->clientService    = $clientService;
    }

    public function index(ClientRepository $clientRepository)
    {
        $clients = $clientRepository->paginate(5);
        return view('admin.clients.index', compact('clients'));
    }
    public function create()
    {
        return view('admin.clients.create');
    }
    public function store(AdminClientRequest $request)
    {
        $data = $request->all();
        $this->clientService->create($data);

        return redirect()->route('admin.clients.index');
    }
    
    public function edit($id)
    {
        $client = $this->repository->find($id);

        /*
         * Foi colocado o lists pois o BaseRepository ja contem est método por padrao nao
         * podendo sobrescrever
         */

        return view('admin.clients.edit',compact('client'));
    }


    /**
     * @param AdminClientRequest $request
     * @param $id
     * @return mixed
     */
    public function update(AdminClientRequest $request, $id)
    {
        $data = $request->all();
        $this->clientService->update($data,$id);


        return redirect()->route('admin.clients.index');
    }

    public function destroy($id)
    {
        $this->repository->delete($id);
        return redirect()->route('admin.clients.index');
    }
}

resources/views/admin/clients/_form.blade.php
<!-- Name Form Input -->
<div class="form-group">
    {!! Form::label('name','Nome:') !!}
    {!! Form::text('user[name]',null,['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('email','E-Mail:') !!}
    {!! Form::text('user[email]',null,['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('phone','Telefone:') !!}
    {!! Form::text('phone',null,['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('address','Endereço:') !!}
    {!! Form::textarea('address',null,['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('city','Cidade:') !!}
    {!! Form::text('city',null,['class'=>'form-control']) !!}
</div>


<div class="form-group">
    {!! Form::label('state','Estado:') !!}
    {!! Form::text('state',null,['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('zipcode','Cep:') !!}
    {!! Form::text('zipcode',null,['class'=>'form-control']) !!}
</div>

resources/views/admin/clients/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h3>
            Categorias
        </h3>

        @include('errors._check')

        {!! Form::open(['route'=>'admin.clients.store']) !!}

        @include('admin.clients._form')

        <div class="form-group">
            {!! Form::submit('Salvar',['class'=>'btn btn-primary']) !!}
        </div>

        {!! Form::close() !!}

    </div>
@endsection

resources/views/admin/clients/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h3>
            Editando Ciente {{$client->user->name}}
        </h3>

        @include('errors._check')

        {!! Form::model($client,['route'=>['admin.clients.update',$client->id]]) !!}

        @include('admin.clients._form')

        <div class="form-group">
            {!! Form::submit('Salvar',['class'=>'btn btn-primary']) !!}
        </div>

        {!! Form::close() !!}

    </div>
@endsection

resources/views/admin/clients/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h3>
        Clients
    </h3>

    <a href="{{route('admin.clients.create')}}" class="btn btn-default">Adicionar</a>
    <br/> <br/>

    <table class="table table-bordered">
        <thead>
        <tr>
            <th>ID</th>
            <th>Nome</th>
            <th>Telefone</th>
            <th>Ação</th>
        </tr>
        </thead>
        <tbody>
        @foreach($clients as $client)
        <tr>
            <td>{{$client->id}}</td>
            <td>{{$client->user->name}}</td>
            <td>{{$client->phone}}</td>
            <td>
                <a class="btn btn-info btn-xs" href="{{route('admin.clients.edit',$client->id)}}">Editar</a>
                <a class="btn btn-danger btn-xs" href="{{route('admin.clients.destroy',$client->id)}}">Excluir</a></td>
        </tr>
        @endforeach
        </tbody>

    </table>

    {!! $clients->render() !!}
</div>
@endsection