app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['middleware' => 'web'], function() {


    Route::get('/', function () {
        return view('welcome');
    });
    Route::get('/home', 'HomeController@index');

    Route::auth();

    Route::group(['prefix' => 'admin','middleware'=>'auth.checkrole:admin', 'as' => 'admin.'], function() {

        Route::get('categories', ['as' => 'categories.index', 'uses' => 'CategoriesController@index']);
        Route::get('categories/create', ['as' => 'categories.create', 'uses' => 'CategoriesController@create']);
        Route::get('categories/edit/{id}', ['as' => 'categories.edit', 'uses' => 'CategoriesController@edit']);
        Route::post('categories/store', ['as' => 'categories.store', 'uses' => 'CategoriesController@store']);
        Route::post('categories/update/{id}', ['as' => 'categories.update', 'uses' => 'CategoriesController@update']);

        Route::get('clients', ['as' => 'clients.index', 'uses' => 'ClientsController@index']);
        Route::get('clients/create', ['as' => 'clients.create', 'uses' => 'ClientsController@create']);
        Route::get('clients/edit/{id}', ['as' => 'clients.edit', 'uses' => 'ClientsController@edit']);
        Route::get('clients/destroy/{id}', ['as' => 'clients.destroy', 'uses' => 'ClientsController@destroy']);
        Route::post('clients/store', ['as' => 'clients.store', 'uses' => 'ClientsController@store']);
        Route::post('clients/update/{id}', ['as' => 'clients.update', 'uses' => 'ClientsController@update']);

        Route::get('products', ['as' => 'products.index', 'uses' => 'ProductsController@index']);
        Route::get('products/create', ['as' => 'products.create', 'uses' => 'ProductsController@create']);
        Route::get('products/edit/{id}', ['as' => 'products.edit', 'uses' => 'ProductsController@edit']);
        Route::post('products/store', ['as' => 'products.store', 'uses' => 'ProductsController@store']);
        Route::post('products/update/{id}', ['as' => 'products.update', 'uses' => 'ProductsController@update']);
        Route::get('products/destroy/{id}', ['as' => 'products.destroy', 'uses' => 'ProductsController@destroy']);

        Route::get('orders', ['as' => 'orders.index', 'uses' => 'OrdersController@index']);
        Route::get('orders/{id}', ['as' => 'orders.edit', 'uses' => 'OrdersController@edit']);
        Route::post('orders/update/{id}', ['as' => 'orders.update', 'uses' => 'OrdersController@update']);

        Route::get('cupoms', ['as' => 'cupoms.index', 'uses' => 'CupomsController@index']);
        Route::get('cupoms/create', ['as' => 'cupoms.create', 'uses' => 'CupomsController@create']);
        Route::post('cupoms/store', ['as' => 'cupoms.store', 'uses' => 'CupomsController@store']);



    });

    Route::group(['prefix' => 'customer', 'as' => 'customer.'], function() {

        Route::get('order', ['as' => 'order.index', 'uses' => 'CheckoutController@index']);
        Route::get('order/create', ['as' => 'order.create', 'uses' => 'CheckoutController@create']);
        Route::post('order/store', ['as' => 'order.store', 'uses' => 'CheckoutController@store']);

    });
    Route::group(['middleware'=>'cors'], function() {

        Route::post('oauth/access_token', function () {
            return Response::json(Authorizer::issueAccessToken());
        });

        Route::group(['prefix' => 'api', 'as' => 'api.', 'middleware' => 'oauth'], function () {

            Route::group(['prefix' => 'client', 'as' => 'client.', 'middleware' => 'oauth.checkrole:client'], function () {
                Route::resource('order', 'Api\Client\ClientCheckoutController', ['except' => ['create', 'edit', 'destroy']]);
                Route::get('products','Api\Client\ClientProductController@index');
            });

            Route::group(['prefix' => 'deliveryman', 'as' => 'deliveryman.', 'middleware' => 'oauth.checkrole:deliveryman'], function () {
                Route::resource('order', 'Api\Deliveryman\DeliverymanCheckoutController', ['except' => ['create', 'edit', 'destroy', 'store']]);
                Route::patch('order/{id}/update-status', [
                    'uses' => 'Api\Deliveryman\DeliverymanCheckoutController@updateStatus',
                    'as' => 'orders.update_status'
                ]);
                Route::post('order/{id}/geo',['as'=>'orders.geo','uses'=>'Api\Deliveryman\DeliverymanCheckoutController@geo']);
            });

            Route::get('authenticated','Api\UserController@authenticated');
            Route::patch('device_token','Api\UserController@updateDeviceToken');
            Route::get('cupom/{code}','Api\CupomController@show');
        });

    });
});

app/Models/Product.php
<?php

namespace CodeDelivery\Models;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Product extends Model implements Transformable
{
    use TransformableTrait;

    //
    protected $fillable = [
        'category_id',
        'name',
        'description',
        'price'
    ];

    public function category()
    {
        return $this->belongsTo(Product::class);
    }

}

app/Http/Controllers/ProductsController.php
<?php

namespace CodeDelivery\Http\Controllers;

use CodeDelivery\Http\Requests\AdminProductRequest;
use CodeDelivery\Repositories\CategoryRepository;
use CodeDelivery\Repositories\ProductRepository;
use CodeDelivery\Http\Requests;
use Illuminate\Http\Request;
use Illuminate\Routing\Redirector;

class ProductsController extends Controller
{
    public function __construct(ProductRepository $produtctRepository, CategoryRepository $categoryRepository)
    {
        $this->repository = $produtctRepository;
        $this->categoryRepository = $categoryRepository;
    }

    public function index(ProductRepository $produtctRepository)
    {
        $products = $produtctRepository->paginate(5);
        return view('admin.products.index',compact('products'));
    }
    public function create()
    {
        $categories = $this->categoryRepository->lists('name','id');
        return view('admin.products.create',compact('categories'));
    }
    public function store(AdminProductRequest $request)
    {
        $data = $request->all();
        $this->repository->create($data);

        return redirect()->route('admin.products.index');
    }
    
    public function edit($id)
    {
        $product = $this->repository->find($id);

        /*
         * Foi colocado o lists pois o BaseRepository ja contem est método por padrao nao
         * podendo sobrescrever
         */
        $categories = $this->categoryRepository->lists('name','id');

        return view('admin.products.edit',compact('product','categories'));
    }


    public function update(AdminProductRequest $request, $id)
    {
        $data = $request->all();
        $this->repository->update($data,$id);

        return redirect()->route('admin.products.index');
    }

    public function destroy($id)
    {
        $this->repository->delete($id);


        return redirect()->route('admin.products.index');
    }
}

resources/views/admin/products/_form.blade.php
<!-- Name Form Input -->
<div class="form-group">
    {!! Form::label('Category','Categorias:') !!}
    {!! Form::select('category_id',$categories,null,['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('Name','Nome:') !!}
    {!! Form::text('name',null,['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('description','Descrição:') !!}
    {!! Form::textarea('description',null,['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('price','Preço:') !!}
    {!! Form::text('price',null,['class'=>'form-control']) !!}
</div>

resources/views/admin/products/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h3>
            Produto
        </h3>

        @include('errors._check')

        {!! Form::open(['route'=>'admin.products.store']) !!}

        @include('admin.products._form')

        <div class="form-group">
            {!! Form::submit('Salvar',['class'=>'btn btn-primary']) !!}
        </div>

        {!! Form::close() !!}

    </div>
@endsection

resources/views/admin/products/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h3>
            Editando Produto {{$product->name}}
        </h3>

        @include('errors._check')

        {!! Form::model($product,['route'=>['admin.products.update',$product->id]]) !!}

        @include('admin.products._form')

        <div class="form-group">
            {!! Form::submit('Salvar',['class'=>'btn btn-primary']) !!}
        </div>

        {!! Form::close() !!}

    </div>
@endsection

resources/views/admin/products/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h3>
        Produtos
    </h3>

    <a href="{{route('admin.products.create')}}" class="btn btn-default">Adicionar</a>
    <br/>
    <br/>

    <table class="table table-bordered">
        <thead>
        <tr>
            <th>ID</th>
            <th>Nome</th>
            <th>Categoria</th>
            <th>Ação</th>
        </tr>
        </thead>
        <tbody>
        @foreach($products as $product)
        <tr>
            <td>{{$product->id}}</td>
            <td>{{$product->name}}</td>
            <td>{{$product->category->name}}</td>
            <td>
                <a class="btn btn-info btn-xs" href="{{route('admin.products.edit',$product->id)}}">Editar</a>
                <a class="btn btn-danger btn-xs" href="{{route('admin.products.destroy',$product->id)}}">Excluir</a></td>
        </tr>
        @endforeach
        </tbody>

    </table>

    {!! $products->render() !!}
</div>
@endsection