app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['middleware' => 'web'], function() {


    Route::get('/', function () {
        return view('welcome');
    });
    Route::get('/home', 'HomeController@index');

    Route::auth();

    Route::group(['prefix' => 'admin','middleware'=>'auth.checkrole:admin', 'as' => 'admin.'], function() {

        Route::get('categories', ['as' => 'categories.index', 'uses' => 'CategoriesController@index']);
        Route::get('categories/create', ['as' => 'categories.create', 'uses' => 'CategoriesController@create']);
        Route::get('categories/edit/{id}', ['as' => 'categories.edit', 'uses' => 'CategoriesController@edit']);
        Route::post('categories/store', ['as' => 'categories.store', 'uses' => 'CategoriesController@store']);
        Route::post('categories/update/{id}', ['as' => 'categories.update', 'uses' => 'CategoriesController@update']);

        Route::get('clients', ['as' => 'clients.index', 'uses' => 'ClientsController@index']);
        Route::get('clients/create', ['as' => 'clients.create', 'uses' => 'ClientsController@create']);
        Route::get('clients/edit/{id}', ['as' => 'clients.edit', 'uses' => 'ClientsController@edit']);
        Route::get('clients/destroy/{id}', ['as' => 'clients.destroy', 'uses' => 'ClientsController@destroy']);
        Route::post('clients/store', ['as' => 'clients.store', 'uses' => 'ClientsController@store']);
        Route::post('clients/update/{id}', ['as' => 'clients.update', 'uses' => 'ClientsController@update']);

        Route::get('products', ['as' => 'products.index', 'uses' => 'ProductsController@index']);
        Route::get('products/create', ['as' => 'products.create', 'uses' => 'ProductsController@create']);
        Route::get('products/edit/{id}', ['as' => 'products.edit', 'uses' => 'ProductsController@edit']);
        Route::post('products/store', ['as' => 'products.store', 'uses' => 'ProductsController@store']);
        Route::post('products/update/{id}', ['as' => 'products.update', 'uses' => 'ProductsController@update']);
        Route::get('products/destroy/{id}', ['as' => 'products.destroy', 'uses' => 'ProductsController@destroy']);

        Route::get('orders', ['as' => 'orders.index', 'uses' => 'OrdersController@index']);
        Route::get('orders/{id}', ['as' => 'orders.edit', 'uses' => 'OrdersController@edit']);
        Route::post('orders/update/{id}', ['as' => 'orders.update', 'uses' => 'OrdersController@update']);

        Route::get('cupoms', ['as' => 'cupoms.index', 'uses' => 'CupomsController@index']);
        Route::get('cupoms/create', ['as' => 'cupoms.create', 'uses' => 'CupomsController@create']);
        Route::post('cupoms/store', ['as' => 'cupoms.store', 'uses' => 'CupomsController@store']);



    });

    Route::group(['prefix' => 'customer', 'as' => 'customer.'], function() {

        Route::get('order', ['as' => 'order.index', 'uses' => 'CheckoutController@index']);
        Route::get('order/create', ['as' => 'order.create', 'uses' => 'CheckoutController@create']);
        Route::post('order/store', ['as' => 'order.store', 'uses' => 'CheckoutController@store']);

    });
    Route::group(['middleware'=>'cors'], function() {

        Route::post('oauth/access_token', function () {
            return Response::json(Authorizer::issueAccessToken());
        });

        Route::group(['prefix' => 'api', 'as' => 'api.', 'middleware' => 'oauth'], function () {

            Route::group(['prefix' => 'client', 'as' => 'client.', 'middleware' => 'oauth.checkrole:client'], function () {
                Route::resource('order', 'Api\Client\ClientCheckoutController', ['except' => ['create', 'edit', 'destroy']]);
                Route::get('products','Api\Client\ClientProductController@index');
            });

            Route::group(['prefix' => 'deliveryman', 'as' => 'deliveryman.', 'middleware' => 'oauth.checkrole:deliveryman'], function () {
                Route::resource('order', 'Api\Deliveryman\DeliverymanCheckoutController', ['except' => ['create', 'edit', 'destroy', 'store']]);
                Route::patch('order/{id}/update-status', [
                    'uses' => 'Api\Deliveryman\DeliverymanCheckoutController@updateStatus',
                    'as' => 'orders.update_status'
                ]);
                Route::post('order/{id}/geo',['as'=>'orders.geo','uses'=>'Api\Deliveryman\DeliverymanCheckoutController@geo']);
            });

            Route::get('authenticated','Api\UserController@authenticated');
            Route::patch('device_token','Api\UserController@updateDeviceToken');
            Route::get('cupom/{code}','Api\CupomController@show');
        });

    });
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Laravel</title>

    <!-- Fonts -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css" integrity="sha384-XdYbMnZ/QjLh6iI4ogqCTaIjrFk87ip+ekIjefZch0Y+PvJ8CDYtEs1ipDmPorQ+" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700">

    <!-- Styles -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    {{-- <link href="{{ elixir('css/app.css') }}" rel="stylesheet"> --}}

    <style>
        body {
            font-family: 'Lato';
        }

        .fa-btn {
            margin-right: 6px;
        }
    </style>
</head>
<body id="app-layout">
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    Laravel
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    <li><a href="{{ url('/home') }}">Home</a></li>
                    @if(Auth::user())
                        @if(Auth::user()->role == "admin")
                            <li><a href="{{ route('admin.categories.index') }}">Categorias</a></li>
                            <li><a href="{{ route('admin.products.index') }}">Produtos</a></li>
                            <li><a href="{{ route('admin.clients.index') }}">Clientes</a></li>
                            <li><a href="{{ route('admin.orders.index') }}">Pedidos</a></li>
                            <li><a href="{{ route('admin.cupoms.index') }}">Cupoms</a></li>
                        @elseif(Auth::user()->role == "client")
                            <li><a href="{{ route('customer.order.index') }}">Meus Pedidos</a></li>
                        @endif
                    @endif
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ url('/login') }}">Login</a></li>
                        <li><a href="{{ url('/register') }}">Register</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{{ url('/logout') }}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>

    @yield('content')

    <!-- JavaScripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.min.js" integrity="sha384-I6F5OKECLVtK/BL+8iSLDEHowSAfUo76ZL9+kGAgTRdiByINKJaqTPH/QVNS1VDb" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    {{-- <script src="{{ elixir('js/app.js') }}"></script> --}}

    @yield('post-script')
</body>
</html>